<?php

/**
 * Robots.txt Generator
 *
 * @package Lemur\SEO
 */

declare(strict_types=1);

namespace Lemur\SEO;

/**
 * Customizes robots.txt output
 */
class Robots
{
    /**
     * Initialize the module
     */
    public static function init(): void
    {
        add_filter('robots_txt', [self::class, 'customizeRobotsTxt'], 10, 2);
    }

    /**
     * Customize robots.txt content
     */
    public static function customizeRobotsTxt(string $output, bool $public): string
    {
        // If site is not public, keep WordPress default (Disallow all)
        if (!$public) {
            return $output;
        }

        $site_url = home_url('/');
        $lines = [];

        // Main bot rules
        $lines[] = '# Lemur Escalade - robots.txt';
        $lines[] = '# Generated by Lemur Theme';
        $lines[] = '';

        // All bots
        $lines[] = 'User-agent: *';
        $lines[] = 'Allow: /';
        $lines[] = '';
        $lines[] = '# WordPress admin and includes';
        $lines[] = 'Disallow: /wp-admin/';
        $lines[] = 'Allow: /wp-admin/admin-ajax.php';
        $lines[] = 'Disallow: /wp-includes/';
        $lines[] = '';
        $lines[] = '# Common WordPress files';
        $lines[] = 'Disallow: /readme.html';
        $lines[] = 'Disallow: /license.txt';
        $lines[] = 'Disallow: /xmlrpc.php';
        $lines[] = '';
        $lines[] = '# Search results';
        $lines[] = 'Disallow: /*?s=';
        $lines[] = 'Disallow: /search/';
        $lines[] = '';
        $lines[] = '# Login and registration';
        $lines[] = 'Disallow: /wp-login.php';
        $lines[] = 'Disallow: /wp-register.php';
        $lines[] = '';
        $lines[] = '# Member area (protected content - MUST NOT be indexed)';
        $lines[] = 'Disallow: /espace-membre/';
        $lines[] = 'Disallow: /annuaire/';
        $lines[] = 'Disallow: /documents/';
        $lines[] = 'Disallow: /todo-list/';
        $lines[] = 'Disallow: /calendrier-membres/';
        $lines[] = '';
        $lines[] = '# Feeds (optional)';
        $lines[] = '# Disallow: /feed/';
        $lines[] = '# Disallow: /comments/feed/';
        $lines[] = '';
        $lines[] = '# Trackback';
        $lines[] = 'Disallow: /trackback/';
        $lines[] = 'Disallow: */trackback/';
        $lines[] = '';
        $lines[] = '# Query parameters to avoid duplicate content';
        $lines[] = 'Disallow: /*?replytocom=';
        $lines[] = 'Disallow: /*?p=';
        $lines[] = '';

        // Block AI crawlers (optional - uncomment to enable)
        $lines[] = '# AI Crawlers (uncomment to block)';
        $lines[] = '# User-agent: GPTBot';
        $lines[] = '# Disallow: /';
        $lines[] = '# User-agent: ChatGPT-User';
        $lines[] = '# Disallow: /';
        $lines[] = '# User-agent: CCBot';
        $lines[] = '# Disallow: /';
        $lines[] = '# User-agent: anthropic-ai';
        $lines[] = '# Disallow: /';
        $lines[] = '# User-agent: Claude-Web';
        $lines[] = '# Disallow: /';
        $lines[] = '';

        // Crawl-delay for less aggressive crawlers
        $lines[] = '# Crawl delay for less aggressive crawlers';
        $lines[] = 'User-agent: Bingbot';
        $lines[] = 'Crawl-delay: 1';
        $lines[] = '';
        $lines[] = 'User-agent: Yandex';
        $lines[] = 'Crawl-delay: 2';
        $lines[] = '';

        // Sitemap
        $lines[] = '# Sitemap';
        $lines[] = 'Sitemap: ' . $site_url . 'wp-sitemap.xml';
        $lines[] = '';

        // Host
        $lines[] = '# Preferred domain';
        $lines[] = 'Host: ' . wp_parse_url($site_url, PHP_URL_HOST);

        return implode("\n", $lines);
    }

    /**
     * Add X-Robots-Tag header for specific pages
     */
    public static function addRobotsHeader(): void
    {
        // Already handled by MetaTags module via meta tags
        // This is for HTTP header level control if needed
        if (is_search() || is_404()) {
            header('X-Robots-Tag: noindex, follow', true);
        }
    }
}
